import type {
  AcademicUnit,
  AcademicUnitKind,
  Curriculum,
  CurriculumSubject,
  Institution,
  PrerequisiteEdge,
  PrerequisiteKind,
  Program,
  Term,
} from '@/domain/types'

/**
 * The portable academic catalog, as it exists on disk.
 *
 * Generated by `scripts/generate-catalog.mjs` from the same research JSON that
 * produces `supabase/seed.sql`, so the two adapters cannot drift about what a
 * plan says. This module only READS it — reference data is never authored by
 * the student, in any mode.
 *
 * Ids here are stable slugs (`utn/utn-frro/isi/Plan 2023`), not Postgres uuids.
 * `docs/vault-format.md` is explicit that the two formats must not be assumed
 * interchangeable; a future sync maps between them deliberately.
 */

interface RawCurriculumRef {
  id: string
  version: string
  name: string
}

interface RawProgram {
  slug: string
  name: string
  degreeType?: string | null
  degree_type?: string | null
  durationHint?: string | null
  curricula: RawCurriculumRef[]
}

interface RawAcademicUnit {
  slug: string
  kind: string
  name: string
  programs: RawProgram[]
}

interface RawInstitution {
  slug: string
  name: string
  shortName?: string
  country?: string
  academicUnits: RawAcademicUnit[]
}

interface RawSubject {
  id: string
  code: string | null
  name: string
  normalizedName: string
  yearLevel: number
  term: string
  credits: number | null
  elective: boolean
  displayOrder: number
  prerequisites: { subjectId: string; kind: string }[]
}

export interface RawCurriculum {
  formatVersion: number
  id: string
  institution: { slug: string; name: string }
  academicUnit: { slug: string; name: string }
  program: { slug: string; name: string }
  name: string
  version: string
  sourceUrl: string | null
  sourceKind: string | null
  retrievedAt: string | null
  prerequisitesKnown: boolean
  prerequisitesNote: string | null
  subjects: RawSubject[]
}

export interface PortableCatalog {
  institutions: RawInstitution[]
  curricula: Map<string, RawCurriculum>
}

/**
 * Load the catalog from a directory.
 *
 * Takes a reader rather than importing `node:fs`, and the parameter is required
 * rather than optional on purpose: an optional Node fallback would put
 * `node:fs` in the module graph of a file the browser bundle imports, and the
 * failure would appear at build time in someone else's week.
 */
export interface CatalogReader {
  readFile(path: string): Promise<string>
  readDir(path: string): Promise<string[]>
}

export async function loadPortableCatalog(
  dir: string,
  reader: CatalogReader,
): Promise<PortableCatalog> {
  const readFile = (p: string) => reader.readFile(p)
  const readDir = (p: string) => reader.readDir(p)

  const root = JSON.parse(await readFile(`${dir}/institutions.json`)) as {
    institutions: RawInstitution[]
  }

  const curricula = new Map<string, RawCurriculum>()
  for (const file of await readDir(`${dir}/curricula`)) {
    if (!file.endsWith('.json')) continue
    const parsed = JSON.parse(await readFile(`${dir}/curricula/${file}`)) as RawCurriculum
    curricula.set(parsed.id, parsed)
  }

  return { institutions: root.institutions, curricula }
}

// --- mapping onto domain types ----------------------------------------------

export function toInstitution(raw: RawInstitution): Institution {
  return {
    id: raw.slug,
    slug: raw.slug,
    name: raw.name,
    shortName: raw.shortName ?? raw.slug.toUpperCase(),
    country: raw.country ?? 'AR',
  }
}

export function toAcademicUnit(raw: RawAcademicUnit, institutionId: string): AcademicUnit {
  return {
    id: raw.slug,
    institutionId,
    parentId: null,
    kind: raw.kind as AcademicUnitKind,
    name: raw.name,
    slug: raw.slug,
  }
}

export function toProgram(raw: RawProgram, academicUnitId: string): Program {
  return {
    id: raw.slug,
    academicUnitId,
    name: raw.name,
    degreeType: raw.degreeType ?? raw.degree_type ?? 'grado',
    durationHint: raw.durationHint ?? null,
  }
}

export function toCurriculum(raw: RawCurriculum): Curriculum {
  const kind = raw.sourceKind
  return {
    id: raw.id,
    programId: raw.program.slug,
    name: raw.name,
    version: raw.version,
    sourceUrl: raw.sourceUrl,
    sourceKind: kind === 'html' || kind === 'pdf' || kind === 'manual' ? kind : null,
    sourceFetchedAt: raw.retrievedAt,
  }
}

export function toCurriculumSubject(raw: RawSubject, curriculumId: string): CurriculumSubject {
  return {
    id: raw.id,
    curriculumId,
    // The catalog keys subjects by their in-plan id; there is no separate
    // shared-subject table locally, so the two coincide.
    subjectId: raw.id,
    code: raw.code,
    name: raw.name,
    normalizedName: raw.normalizedName,
    yearLevel: raw.yearLevel,
    term: raw.term as Term,
    credits: raw.credits,
    elective: raw.elective,
    displayOrder: raw.displayOrder,
  }
}

/** Flatten per-subject prerequisites into the edge list the domain works with. */
export function toPrerequisiteEdges(raw: RawCurriculum): PrerequisiteEdge[] {
  const edges: PrerequisiteEdge[] = []
  for (const subject of raw.subjects) {
    for (const p of subject.prerequisites) {
      edges.push({
        curriculumSubjectId: subject.id,
        requiredCurriculumSubjectId: p.subjectId,
        kind: p.kind as PrerequisiteKind,
      })
    }
  }
  return edges
}
